/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.tdeacontruccionm.gestionperfilusuario;

import javax.swing.SwingUtilities;

/**
 *
 * @author danie
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiGestionProductos = new javax.swing.JMenuItem();
        jmiGestionPerfilUsuario = new javax.swing.JMenuItem();
        jmiRegistroProductosAgricolas = new javax.swing.JMenuItem();
        jmiReportedeVentas = new javax.swing.JMenuItem();
        jmiBusquedadeReportesAgricolas = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jmiSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiSalir.setMnemonic('s');
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmiSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Administar ");

        jmiGestionProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiGestionProductos.setMnemonic('p');
        jmiGestionProductos.setText("Gestión Productos");
        jmiGestionProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionProductosActionPerformed(evt);
            }
        });
        jMenu2.add(jmiGestionProductos);

        jmiGestionPerfilUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiGestionPerfilUsuario.setMnemonic('p');
        jmiGestionPerfilUsuario.setText("Gestión Perfil Usuario");
        jmiGestionPerfilUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionPerfilUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(jmiGestionPerfilUsuario);

        jmiRegistroProductosAgricolas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiRegistroProductosAgricolas.setMnemonic('p');
        jmiRegistroProductosAgricolas.setText("Registro de Productos Agricolas");
        jmiRegistroProductosAgricolas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistroProductosAgricolasActionPerformed(evt);
            }
        });
        jMenu2.add(jmiRegistroProductosAgricolas);

        jmiReportedeVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiReportedeVentas.setMnemonic('p');
        jmiReportedeVentas.setText("Reporte de Ventas");
        jmiReportedeVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReportedeVentasActionPerformed(evt);
            }
        });
        jMenu2.add(jmiReportedeVentas);

        jmiBusquedadeReportesAgricolas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiBusquedadeReportesAgricolas.setText("Busqueda de Reportes Agricolas");
        jmiBusquedadeReportesAgricolas.setToolTipText("p");
        jmiBusquedadeReportesAgricolas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBusquedadeReportesAgricolasActionPerformed(evt);
            }
        });
        jMenu2.add(jmiBusquedadeReportesAgricolas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiGestionProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionProductosActionPerformed
        // TODO add your handling code here:
         SwingUtilities.invokeLater(() -> new OrderManagement().setVisible(true));
         
    }//GEN-LAST:event_jmiGestionProductosActionPerformed

    private void jmiGestionPerfilUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionPerfilUsuarioActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> new UserProfileManagement().setVisible(true));
    }//GEN-LAST:event_jmiGestionPerfilUsuarioActionPerformed

    private void jmiRegistroProductosAgricolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistroProductosAgricolasActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> new AgriculturalProductRegistration().setVisible(true));
        
    }//GEN-LAST:event_jmiRegistroProductosAgricolasActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiReportedeVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReportedeVentasActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> new SalesReport ().setVisible(true));
    }//GEN-LAST:event_jmiReportedeVentasActionPerformed

    private void jmiBusquedadeReportesAgricolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBusquedadeReportesAgricolasActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> new AgriculturalProductsSearch().setVisible(true));
    }//GEN-LAST:event_jmiBusquedadeReportesAgricolasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jmiBusquedadeReportesAgricolas;
    private javax.swing.JMenuItem jmiGestionPerfilUsuario;
    private javax.swing.JMenuItem jmiGestionProductos;
    private javax.swing.JMenuItem jmiRegistroProductosAgricolas;
    private javax.swing.JMenuItem jmiReportedeVentas;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
}
